import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

type User = {
  firstName: string;
  lastName: string;
  email: string;
  phone: number;
  salary: string;
};

interface HomeProps {
  userData: User;
  updateUserProperties: (
    e: React.FormEvent<HTMLFormElement>,
    nextpage: string
  ) => void;
}

export default function Home({ updateUserProperties, userData }: HomeProps) {
  function validateUserName(value: string) {}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by Yorick ten Feld' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>welcome to Buena</h1>
        <p>
          Buena cares for your apartments, tenants, and every task that comes
          with being a landlord. That&apos;s more time for you. Let&apos;s get
          started with some easy questions.
        </p>
        <form onSubmit={(e) => updateUserProperties(e, 'contact')}>
          <label htmlFor='firstName'>First Name:</label>
          <input
            type='text'
            id='firstName'
            name='firstName'
            defaultValue={userData.firstName}
            onChange={(e) => validateUserName(e.target.value)}
          />
          <label htmlFor='lastName'>Last Name:</label>
          <input
            type='text'
            id='lastName'
            name='lastName'
            defaultValue={userData.lastName}
            onChange={(e) => validateUserName(e.target.value)}
          />
          <button>next</button>
        </form>
      </main>
    </>
  );
}
