import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  const videoUrl =
    'https://framerusercontent.com/assets/375wnZVxAp3GMWD38xzYEjS8Sc.mp4';

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by Yorick ten Feld' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <section className='banner'>
        <div>
          <h1>Buena</h1>
          <h2>Property management as it should be</h2>
        </div>
        <p>
          Buena cares for your apartments, tenants, and every task that comes
          with being a landlord. That&apos;s more time for you. Let&apos;s get
          started with some easy questions.
        </p>
      </section>
      <Link className='linkButton getStarted' href='/name'>
        Get Started
      </Link>
      <Link className='linkButton getStarted' href='#detailsSection'>
        More Information
      </Link>

      <div className='video-player'>
        <video
          autoPlay
          loop
          muted
          style={{
            height: 'auto',
          }}
        >
          <source src={videoUrl} type='video/mp4' className='video' />
          Your browser does not support the video tag.
        </video>
        <div className='shadow'></div>
      </div>

      <main>
        <article id='detailsSection'>
          <h2>Reinventing Renting</h2>
          <p>
            Owning property or living in a rental apartment affects the majority
            of our society, whether as landlords or tenants, as a financial
            investment or as a first home. Property ownership has always been a
            proven way to invest in your retirement. However, ownership also
            comes with responsibilities. Owners must be well-versed in many new
            areas to stay on top of things. Renting requires appealing photos,
            detailed advertisements, handling inquiries, organizing viewings,
            evaluating applications, creating rental agreements, complying with
            regulations, monitoring payments, and preparing utility cost
            statements. All of this must be repeated for each new tenant.
          </p>
          <br />
          <p>
            Thus, property ownership quickly becomes time-consuming, opaque, and
            costly, and landlords forget why they decided to buy an apartment in
            the first place: to invest money. But for tenants searching for a
            new apartment, there are also many challenges and lack of
            transparency. The housing market is often characterized by high
            demand, and tenants must compete for their dream apartment. Whether
            its moving to a new city, searching for a new home for the family,
            or taking the step of moving in with a partner - these are
            significant life events that unfortunately are often accompanied by
            stress and worries.
          </p>
          <br />
          <p>
            Owners are looking for a convenient solution and a reliable partner
            for renting and managing their properties. Tenants wish to quickly
            and easily find their affordable dream apartment and a partner who
            genuinely addresses their problems. Buena is the solution for owners
            and tenants. Buena takes on all responsibilities from the owners and
            enables tenants to quickly and easily find, visit, and finally start
            living in their new home.
          </p>
        </article>
      </main>
    </>
  );
}
